# Generated by Django 3.2.16 on 2022-12-01 07:46

from django.db import migrations, models
import polls.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='photo_file',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=polls.utilities.get_timestamp_path),
        ),
    ]
