# Generated by Django 3.2.16 on 2022-12-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_advuser_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='role',
        ),
    ]
